apiVersion: npm.centerionware.app/v1alpha1
kind: NpmApp
metadata:
  name: meet
  namespace: apps
spec:
  repo: https://github.com/livekit-examples/meet
  revision: main

  image: registry.registry.svc.cluster.local:5000/meet

  build:
    installCommand: pnpm install
    buildCommand: pnpm build
  
  run:
    command: pnpm start
    port: 3000

  env:
    LIVEKIT_API_KEY: "replace-me"
    LIVEKIT_API_SECRET: "replace-me"
    LIVEKIT_URL: "wss://your-livekit-instance"

  service:
    annotations:
      netbird.io/expose: "true"
      netbird.io/groups: "media"
      netbird.io/policy: "media"
      netbird.io/resource-name: "meet"
      netbird.io/sourceGroups: "Media-access"