apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: npm-operator

rules:
  - apiGroups: ["npm.centerionware.app"]
    resources: ["npmapps"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]
  
  - apiGroups: ["npm.centerionware.app"]
    resources: ["npmapps/status"]
    verbs: ["get", "update", "patch"]
  
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["*"]
  
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["*"]
  
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["*"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: npm-operator

roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: npm-operator

subjects:
  - kind: ServiceAccount
    name: {{ .Values.serviceAccount.name }}
    namespace: {{ .Values.namespace }}